import { AuthProvider } from "./components/context/AuthContext";
import "./globals.css"
import {poppins} from "./fonts/fonts"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased `}
      >
        <AuthProvider>

        {children}
        </AuthProvider>
        
      </body>
    </html>
  );
}
